### ISSUE TITLE
Problem: cannot set user-agent with cronos

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/defi-wallet-core-rs#484]
can setup user agent in http request

for example)
```
SetHeader(TEXT("User-Agent"), "DefiWalletCore-Agent");
```

**Comment by leejw51crypto** [comment]
ref)
```
const eth = new ethers.providers.JsonRpcProvider(Rpc)
eth.connection.headers = {
'User-Agent': 'CronosPlay-UnrealEngine-Agent'
    'Content-Type': 'application/json; charset=utf-8',
    'Accept': 'application/json',
 ... 
 ```

**Comment by tomtau** [comment]
https://docs.rs/reqwest/latest/reqwest/blocking/struct.ClientBuilder.html#method.user_agent

plus construct the http middleware via https://github.com/gakonst/ethers-rs/blob/3df1527cef7a7de8cbb26a8c98de74348203176b/ethers-providers/src/transports/http.rs#L151

**Comment by tomtau** [comment]
not sure for gRPC and gprc-web clients

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
example code worked, now modifying now

**Comment by leejw51crypto** [comment]
working on test failures
