### ISSUE TITLE
Problem: missing feature of erc 1155 owner

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/defi-wallet-core-rs#497]
add erc 1155 owner

**Comment by damoncro** [comment]
ERC1155 do not has owner function, use getTokenHolders in blockscout instead, check https://github.com/cronos-labs/play-cpp-sdk/issues/149

**Comment by damoncro** [comment]
Or use balance_of https://forum.openzeppelin.com/t/erc1155-check-if-token-owner/8503

**Comment by damoncro** [comment]
Use balance_of is better, check if the user owns those tokens (balance > 0 means owns the token).

**Comment by damoncro** [comment]
Query all owners in one ERC1155 contract maybe not very useful, not to mention the possible huge return data.

**Comment by leejw51crypto** [comment]
ok, agree
i'll use balance_of instead of owner
