### ISSUE TITLE
Problem: missing support for general contract calls

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/defi-wallet-core-rs#517]
add general solidity compiled code deploy,
and call solidity functions

in case, user already have compiled contract code

**Comment by damoncro** [comment]
I worked on it via cpp binding last week by reading abi json file, do we still need to add this feature?

**Comment by leejw51crypto** [comment]
that would be enough, i'll check

**Comment by damoncro** [comment]
My original work here: https://github.com/damoncro/defi-wallet-core-rs/commit/a2660f40f38b872dfb0d2e268aa3261e008b61ab Still WIP.
