### ISSUE TITLE
Problem: missing secure storage option for android

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/defi-wallet-core-rs#764]
write a custom wrapper in Kotlin or Java over the Android security library (like EncryptedFile : https://developer.android.com/topic/security/data ) 
and write wrapper using JNI.

if possible use rust or c++

**Comment by tomtau** [comment]
The wrapper can perhaps expose a similar API to that keyring, i.e. save/get entry with servicename+username. e.g. create/read the encrypted file under the path: [context.filesDir](https://developer.android.com/reference/android/content/Context#getFilesDir())/servicename/username ?

**Comment by leejw51crypto** [comment]
yes, interface will be the same with keyring
